# Generated by Django 3.2 on 2022-09-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='car',
        ),
    ]
